import { Character } from './object-types/character';
import { SPECIES } from './mock-species';

export const CHARACTERS: Character[] = [
    {id: 1, name: 'guy 1', species: SPECIES[0], wound: 10, strain: 10, brawn: 2, agility: 3, intellect: 2, cunning: 4, willpower: 3, presence: 2, astrogation: 0, athletics: 1, brawl: 0, charm: 1, coercion: 0, computers: 3, cool: 2, coordination: 1, coreWorlds: 0, deception: 0, discipline: 3, education: 1, gunnery: 0, leadership: 1, lightsaber: 0, lore: 1, mechanics: 1, medicine: 0, melee: 1, negotiation: 2, outerRim: 0, perception: 1, pilotingP: 0, pilotingS: 0, rangedH: 0, rangedL: 0, resilience: 1, skulduggery: 0, stealth: 4, streetwise: 1, survival: 2, underworld: 0, vigilance: 3, warfare: 0, xenology: 0, notes: 'I Do Work'},
    {id: 1, name: 'girl 3', species: SPECIES[1], wound: 9, strain: 11, brawn: 1, agility: 2, intellect: 5, cunning: 3, willpower: 2, presence: 3, astrogation: 0, athletics: 1, brawl: 0, charm: 1, coercion: 0, computers: 3, cool: 2, coordination: 1, coreWorlds: 0, deception: 0, discipline: 3, education: 1, gunnery: 0, leadership: 1, lightsaber: 0, lore: 1, mechanics: 1, medicine: 0, melee: 1, negotiation: 2, outerRim: 0, perception: 1, pilotingP: 0, pilotingS: 0, rangedH: 0, rangedL: 0, resilience: 1, skulduggery: 0, stealth: 4, streetwise: 1, survival: 2, underworld: 0, vigilance: 3, warfare: 0, xenology: 0, notes: 'I Do Work More'},
    {id: 1, name: 'gym 2', species: SPECIES[2], wound: 11, strain: 9, brawn: 3, agility: 1, intellect: 3, cunning: 1, willpower: 1, presence: 2, astrogation: 0, athletics: 1, brawl: 0, charm: 1, coercion: 0, computers: 3, cool: 2, coordination: 1, coreWorlds: 0, deception: 0, discipline: 3, education: 1, gunnery: 0, leadership: 1, lightsaber: 0, lore: 1, mechanics: 1, medicine: 0, melee: 1, negotiation: 2, outerRim: 0, perception: 1, pilotingP: 0, pilotingS: 0, rangedH: 0, rangedL: 0, resilience: 1, skulduggery: 0, stealth: 4, streetwise: 1, survival: 2, underworld: 0, vigilance: 3, warfare: 0, xenology: 0, notes: 'I Do Work Harder'},
    {id: 1, name: 'jim 4', species: SPECIES[3], wound: 12, strain: 10, brawn: 2, agility: 2, intellect: 1, cunning: 1, willpower: 2, presence: 1, astrogation: 0, athletics: 1, brawl: 0, charm: 1, coercion: 0, computers: 3, cool: 2, coordination: 1, coreWorlds: 0, deception: 0, discipline: 3, education: 1, gunnery: 0, leadership: 1, lightsaber: 0, lore: 1, mechanics: 1, medicine: 0, melee: 1, negotiation: 2, outerRim: 0, perception: 1, pilotingP: 0, pilotingS: 0, rangedH: 0, rangedL: 0, resilience: 1, skulduggery: 0, stealth: 4, streetwise: 1, survival: 2, underworld: 0, vigilance: 3, warfare: 0, xenology: 0, notes: 'I Do Work Faster'},
    {id: 1, name: 'guy 5', species: SPECIES[4], wound: 8, strain: 12, brawn: 1, agility: 3, intellect: 2, cunning: 2, willpower: 4, presence: 2, astrogation: 0, athletics: 1, brawl: 0, charm: 1, coercion: 0, computers: 3, cool: 2, coordination: 1, coreWorlds: 0, deception: 0, discipline: 3, education: 1, gunnery: 0, leadership: 1, lightsaber: 0, lore: 1, mechanics: 1, medicine: 0, melee: 1, negotiation: 2, outerRim: 0, perception: 1, pilotingP: 0, pilotingS: 0, rangedH: 0, rangedL: 0, resilience: 1, skulduggery: 0, stealth: 4, streetwise: 1, survival: 2, underworld: 0, vigilance: 3, warfare: 0, xenology: 0, notes: 'I Do Work Little'},
    {id: 1, name: 'lady 6', species: SPECIES[5], wound: 10, strain: 8, brawn: 4, agility: 1, intellect: 2, cunning: 3, willpower: 3, presence: 4, astrogation: 0, athletics: 1, brawl: 0, charm: 1, coercion: 0, computers: 3, cool: 2, coordination: 1, coreWorlds: 0, deception: 0, discipline: 3, education: 1, gunnery: 0, leadership: 1, lightsaber: 0, lore: 1, mechanics: 1, medicine: 0, melee: 1, negotiation: 2, outerRim: 0, perception: 1, pilotingP: 0, pilotingS: 0, rangedH: 0, rangedL: 0, resilience: 1, skulduggery: 0, stealth: 4, streetwise: 1, survival: 2, underworld: 0, vigilance: 3, warfare: 0, xenology: 0, notes: 'I Do Work Sooner'}
];
